project_id = "cdisjzisxpsnwuycdjri"

[functions.seed_demo]
verify_jwt = true

[functions.update_devex_rate]
verify_jwt = false

[functions.send_weekly_report]
verify_jwt = false

[functions.parse_csv]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.seat-counter]
verify_jwt = false

[functions.create-customer-portal]
verify_jwt = true